bundle_values: true
bundle_where_in: true
filters: Query matches "^(SELECT|INSERT|UPDATE|REPLACE|DELETE|WITH) "
limit: 65536
output: count,query,sum-query-time,avg-query-time,sum-lock-time,avg-lock-time,sum-rows-sent,avg-rows-sent,sum-rows-examined,avg-rows-examined
sort: sum-query-time
reverse: true
